name: base-env
channels:
- defaults
- conda-forge
dependencies:
- mypy=0.981
- pyupgrade=3.10.1
- black=23.3.0
- ruff=0.0.285
- bandit=1.7.5
- tqdm=4.65.0
- pylint=2.16.2
- autoflake=1.7.5
- pip:
  - pydocstringformatter==0.7.3
